### ISSUE TITLE
Swift 编译不通过

### ISSUE THREAD

**Issue by Yu2erer** [renzifeng/ZFDownload#18]
![685c7ccd-a80f-4b0e-8383-3d7ca380c6ba](https://cloud.githubusercontent.com/assets/14922363/25581552/1dbcf5f8-2ebb-11e7-820e-3ca86da20eac.png)

**Comment by ajaysinghthakur** [comment]
you have to add compiler flag  - (-fno-objc-arc) in target -> build phase -> compile source in front of all ASHITTPRequest files.
