### ISSUE TITLE
pod(v1.0.1) 编译错误

### ISSUE THREAD

**Issue by l900416** [renzifeng/ZFDownload#7]
使用pod（v1.0.1）时，出现如下错误：

-->
/xxx/Pods/ZFDownload/ZFDownload/ZFHttpRequest.h:25:9: Could not build module 'ASIHTTPRequest'
## 

XCode version : 7.3.1
OSX : 10.11.6 

Ps：仅仅使用ZFPlayer时 正常

**Comment by l900416** [comment]
可能是两台机子上pod版本不同的原因
command+shift+option+k 清理后可解决，So sorry

**Comment by coderyin** [comment]
遇到相同的问题了
